### ISSUE TITLE
Try goa

### ISSUE THREAD

**Issue by joeblew99** [ngorm/ngorm#1]
Goa is a code generator that fully supports Gorm.

If you can match the postresql API then it would be great because I could use Ql on mobile and cockroaches on the server , whilst using the same code.

Probably worth putting a test with gomobile to check Ql works on android and iOS simulator.
Easiest was to test if to log to a cloud based log system like Google cloud .

**Comment by gernest** [comment]
@joeblew99 postgresql is next on the line!  

logging with ngorm is easy and it is possible to use other providers. There are so much benefits here, and it requires some time to list them all.

Hopefully this lib will reach there!
